#!/bin/sh

commit_message=$(cat "$1")
current_branch=$(git rev-parse --abbrev-ref HEAD)

ESC=$(printf '\033')

case "$current_branch" in
  [0-9]*)
    ticket=$(echo "$current_branch" | cut -d '-' -f 1)
    create_message="refs #${ticket} ${commit_message}"
    echo "$create_message" > "$1"
    ;;
  *)
    printf "${ESC}[91m%s${ESC}[m\n" "  Incorrect branch naming convention."
    exit 1
    ;;
esac
